### ISSUE TITLE
Remove themes completely?

### ISSUE THREAD

**Issue by deltaidea** [vk-x/vk-x-legacy#143]
I think we can remove themes because:
1. The main purpose of this project is ~~to optimize vk.com, not to extend it~~ to optimize vk.com (even through extension), but not to provide such customization features. Only really useful things.
2. There're already many specialized solutions out there regarding vk.com themes.
3. Available themes are out-of-date, and apply incorrectly or have side effects.

**Comment by lucky-ly** [comment]
:+1:
