### ISSUE TITLE
Merge changes from VkOpt

### ISSUE THREAD

**Issue by deltaidea** [vk-x/vk-x-legacy#169]
It's time to get back in sync with [VkOpt](/vkopt/vkopt) and merge their updates into vk-x.

**Comment by Pmmlabs** [comment]
definitely.

**Comment by deltaidea** [comment]
**New estimation: 15 hours.**

**Comment by deltaidea** [comment]
**New estimation: 13 hours.**

**Comment by deltaidea** [comment]
**New estimation: 17 hours.**
It takes ~3 hours to merge one page of commits. 5.5 pages left.

**Comment by deltaidea** [comment]
Let's define the last commit to merge to consider this issue closed for now: VkOpt/VkOpt@4d59aea0a016b84c1a4c791a05bdeccc302a9974.

**Comment by deltaidea** [comment]
**New estimation: 10 hours.**
